[mediaTypes]
  [mediaTypes."text/droplist"]
    suffixes = ["droplist"]

[outputFormats.droplist]
mediatype = "text/droplist"
isPlainText = true

[[params.menu]]
	name = "about"
	url = "documents/about"

[[params.menu]]
	name = "resume"
	url = "resume"

[[params.menu]]
        name = "blog"
        url = "posts/"


[[params.topmenu]]
	name = "about"
	url = "documents/about"

[[params.topmenu]]
	name = "resume"
	url = "resume"

[[params.topmenu]]
        name = "blog"
        url = "posts"

