[mediaTypes]
  [mediaTypes."text/droplist"]
    suffixes = ["droplist"]

[outputFormats.droplist]
mediatype = "text/droplist"
isPlainText = true

[[params.topmenu]]
	name = "resume"
	url = "resume"

[[params.topmenu]]
        name = "blog"
        url = "posts"

